name: Build

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    - run: nuget restore AudioPlaybackConnector.sln

    - run: |
        Start-Job -Init ([ScriptBlock]::Create("Set-Location '$pwd'")) -Script {
          msbuild AudioPlaybackConnector.sln "-p:Configuration=Release;Platform=x64" }
        Get-Job | Wait-Job | Receive-Job
      shell: powershell

    - uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector64
        path: x64/Release/AudioPlaybackConnector64.exe

    - uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector64
        path: x64/Release/AudioPlaybackConnector64.pdb
