name: Build

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: latest

    - name: Restore sln with nuget
      run: nuget restore AudioPlaybackConnector.sln

    - name: Start build jobs
      run: |
        Start-Job -Init ([ScriptBlock]::Create("Set-Location '$pwd'")) -Script {
          msbuild AudioPlaybackConnector.sln "-p:Configuration=Release;Platform=x64" }
        Get-Job | Wait-Job | Receive-Job
      shell: powershell

    - uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector64
        path: x64/Release/AudioPlaybackConnector64.exe

    - uses: actions/upload-artifact@v4
      with:
        name: AudioPlaybackConnector64
        path: x64/Release/AudioPlaybackConnector64.pdb
